### ISSUE TITLE
Pilot - mobile

### ISSUE THREAD

**Issue by cchiara** [adraxyz/help-projects#17]
- [x] switch desktop image with mobile image 
![IMG_51F908196054-1](https://user-images.githubusercontent.com/48411554/80799504-4d3f1300-8ba7-11ea-9e7c-608d16700b05.jpeg) 
replace it with this one ![Mobile_-_Pilot_optimized.png](https://images.zenhubusercontent.com/5eabfc65896abe4b7cf6d5a3/7067e05e-bea1-40fa-9cec-f3e46bb88f4e)

- [x] remove "learn more"
- [x] reduce text column width according to home
- [x] reduce map width accordingly 
- [x]  increase space between coordinates after the map and the next section (the context)
- [x]  images take too long to load 
- [x]  reduce images width accordingly to column width 
- [ ] section "the project" put image before text
- [ ]  remove labels at the end 
![IMG_3187B57C1881-1](https://user-images.githubusercontent.com/48411554/80799921-6b594300-8ba8-11ea-96d8-c10fd193f6f6.jpeg)
- [x] remove final sentence

**Comment by adraxyz** [comment]
@cchiara I would discuss the following points:

> section "the project" put image before text

Why? All section have a textual introduction, we can use a short subtitle so that the section will have title -> subtitle -> image -> description (long text). Are you agree with that suggestion?

> remove labels at the end
Are you sure? That label are short enough to be visible on mobile. The text color ensure a link with the image above so I think we can keep that labels visible on mobile.
